models/__init__.py

__all__ = [
    'user',
    'book',
    'emprestimos'
]

models/book.py
from database import get_connection

class Book:
    def __init__(self, titulo, user_id):
        self.titulo = titulo
        self.user_id = user_id

    def save(self):
        conn = get_connection()
        conn.execute("INSERT INTO books(titulo, user_id) values(?,?)", (self.titulo, self.user_id))
        conn.commit()
        conn.close()
        return True

    @classmethod
    def all(cls):
        conn = get_connection()
        books = conn.execute("SELECT * FROM books").fetchall()
        return books

models/emprestimos.py
from database import get_connection

class Emprestimos:
    def __init__(self, email, titulo, data):
        self.email = email
        self.titulo = titulo
        self.data = data
    def save(self):
        conn = get_connection()
        conn.execute("INSERT INTO emprestimos(email, titulo, data_eptm) values(?,?,?)", (self.email, self.titulo, self.data,))
        conn.commit()
        conn.close()
        return True
    
    @classmethod
    def all(cls):
        conn = get_connection()
        users = conn.execute("SELECT * FROM emprestimos").fetchall()
        return users
    

models/user.py
from database import get_connection

class User:
    def __init__(self, nome, email):
        self.nome = nome
        self.email = email
        
    def save(self):
        conn = get_connection()
        conn.execute("INSERT INTO users(email, nome) values(?,?)", (self.email, self.nome))
        conn.commit()
        conn.close()
        return True
    
    @classmethod
    def all(cls):
        conn = get_connection()
        users = conn.execute("SELECT * FROM users").fetchall()
        return users

app.py
from flask import Flask
from controllers import users, books, emprestimos

app = Flask(__name__)
app.register_blueprint(users.bp)
app.register_blueprint(books.bp)
app.register_blueprint(emprestimos.bp)

controllers/__init__.py

all = [
    'books',
    'users',
    'emprestimos'
]

controllers/books.py
from flask import Flask, render_template, url_for, request, Blueprint, redirect
from models.user import User
from models.book import Book

bp = Blueprint('books', __name__, url_prefix='/books')

@bp.route('/')
def index():
    return render_template('books/index.html', books = Book.all())

@bp.route('/register', methods=['POST', 'GET'])
def register():
    
    if request.method == 'POST':
        titulo = request.form['titulo']
        user = request.form['user']

        book = Book(titulo, user)
        book.save()
        return redirect(url_for('books.index'))


    return render_template('books/register.html', users=User.all())

controllers/emprestimos.py
from flask import render_template, Blueprint, url_for, request, flash, redirect
from models.emprestimos import Emprestimos

# módulo de usuários
bp = Blueprint('emprestimos', __name__, url_prefix='/emprestimos')

@bp.route('/')
def index():
    return render_template('emprestimos/index.html', emprestimos = Emprestimos.all())

@bp.route('/register', methods=['POST', 'GET'])
def register():
    if request.method == 'POST':
        email = request.form['email']
        titulo= request.form['titulo']
        data = request.form['data']

        if not email:
            flash('Email é obrigatório')
        else:
            emprestimo = Emprestimos(email, titulo, data)
            emprestimo.save()
            return redirect(url_for('emprestimos.index'))
    
    return render_template('emprestimos/register.html')

controllers/users.py
from flask import render_template, Blueprint, url_for, request, flash, redirect
from models.user import User

# módulo de usuários
bp = Blueprint('users', __name__, url_prefix='/users')

@bp.route('/')
def index():
    return render_template('users/index.html', users = User.all())

@bp.route('/register', methods=['POST', 'GET'])
def register():
    if request.method == 'POST':
        email = request.form['email']
        nome= request.form['nome']

        if not email:
            flash('Email é obrigatório')
        else:
            user = User(email, nome)
            user.save()
            return redirect(url_for('users.index'))
    
    return render_template('users/register.html')

database/__init__.py
import sqlite3
import os

DATABASE = 'database.db'
dirname = os.path.dirname(os.path.realpath(__file__))

def get_connection():    
    conn = sqlite3.connect(os.path.join(dirname, DATABASE))
    conn.row_factory = sqlite3.Row
    return conn

templates/books/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

    <h1>Lista de Livros</h1>

    <a href="{{url_for('books.register')}}">Adicionar</a>
    <hr>
    {% for book in books %}
    <div style='display: flex; background-color: rgb(194, 153, 206); margin: 7px; border-radius: 15px; justify-content: space-around; color: white; font-family: Arial, Helvetica, sans-serif'>
        <p>{{book.titulo}}</p>
    </div>
    {% endfor %}
    
</body>
</html>

templates/books/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Books - Register</title>
</head>
<body>

    <h1>Registrar Livros</h1>

    <div>
        <h2>Dados</h2>
        <form action="{{url_for('books.register')}}" method="post">
            <input type="text" name="titulo" placeholder="Título" value="{{request.form['titulo']}}">
            <select name="user">
                {% for user in users %}
                    <option value="{{user.id}}">{{user.nome}}</option>    
                {% endfor %}                
            </select>
            <button>Enviar</button>
        </form>
    </div>


    
</body>
</html>

templates/emprestimos/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

    <h1>Lista de Emprestimos</h1>

    <a href="{{url_for('emprestimos.register')}}">Adicionar</a>

    <hr>
    {% for emprestimos in emprestimos %}
    <div style='display: flex; background-color: rgb(194, 153, 206); margin: 7px; border-radius: 15px; justify-content: space-around; color: white; font-family: Arial, Helvetica, sans-serif'>
        <p>{{emprestimos.email}}</p>
       <p>{{emprestimos.titulo}}</p>
       <p>{{emprestimos.data_eptm}}</p>
    </div>
    {% endfor %}
    
</body>
</html>

templates/emprestimos/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
    <h1>Registro de Emprestimos</h1>
    <div>
        <h2>Dados</h2>
        <form action="{{url_for('emprestimos.register')}}" method="post">
            <input type="email" name="email" placeholder="Email" value="{{request.form['email']}}">
            {% with error = get_flashed_messages()  %}
            <span class="warning">{{error[0]}}</span>    
            {% endwith %}    
            <input type="text" name="titulo" placeholder="Titulo" value="{{request.form['titulo']}}">
            <input type="date" name="data" placeholder="Data" value="{{request.form['data']}}">
            <button>Enviar</button>
        </form>
    
    </div>

</body>
</html>

templates/users/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

    <h1>Lista de Usuários</h1>

    <a href="{{url_for('users.register')}}">Adicionar</a>

    <hr>
    {% for user in users %}
    <div style='display: flex; background-color: rgb(194, 153, 206); margin: 7px; border-radius: 15px; justify-content: space-around; color: white; font-family: Arial, Helvetica, sans-serif;'>
        <p>{{user.email}}</p>
        <p>{{user.nome}}</p>
    </div>
    
    {% endfor %}
    
</body>
</html>

templates/users/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
    <h1>Registro de Usuários</h1>
    <div>
        <h2>Dados</h2>
        <form action="{{url_for('users.register')}}" method="post">
            <input type="email" name="email" placeholder="Email" value="{{request.form['email']}}">
            {% with error = get_flashed_messages()  %}
            <span class="warning">{{error[0]}}</span>    
            {% endwith %}    
            <input type="text" name="nome" placeholder="Nome" value="{{request.form['nome']}}">
            <button>Enviar</button>
        </form>
    
    </div>

</body>
</html>

templates/users/teste.html
{% extends 'layout.html' %}

{% block content %}
    <h1>Oi</h1>
{% endblock %}